FROM kong:latest

# root ユーザーとしてコマンドを実行
USER root

RUN mkdir -p /var/lib/apt/lists/partial && chmod -R 755 /var/lib/apt/lists

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y wget

ENV DOCKERIZE_VERSION v0.7.0
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
    